### ISSUE TITLE
Более правильно было бы возвращать тут пустой массив

### ISSUE THREAD

**Issue by denis-cto** [pinahq/framework#12]
https://github.com/pinahq/framework/blob/9d1df5d06a629099c4876b5daa18fc38e62a5580/src/Pina/SQL.php#L962

Таким образом формат результата данной функции всегда будет массив, а не массив или строка. Пусть и пустая.

**Comment by denis-cto** [comment]
Либо вообще выкидывать исключение... Так как не задано откуда выбирать

**Comment by alex-yashin** [comment]
теперь выкидываю там исключение
