### ISSUE TITLE
Откорректировать метод exists - неверно возвращаемые данные

### ISSUE THREAD

**Issue by denis-cto** [pinahq/framework#9]
Метод ->exists() при отсутствии данных возвращает 0, при этом в его описании указано что может вернуть bool или string. Нужно либо возвращать bool, либо убрать его из описания функции, как и string

```php
 /**
     * @return string|bool
     */
    public function exists()
    {
        return $this->limit(1)->count();
    }
```

**Comment by alex-yashin** [comment]
Сделал условие > 0, теперь возвращаемый тип строго bool
